# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: 
     - closed
  push:
    branches:
    - $default-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}