name: Semver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: 
     - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}